---
name: Release

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with: { targets: wasm32-unknown-unknown }
      - uses: Swatinem/rust-cache@v2
      - run: cargo wasm
      - run: cp target/wasm32-unknown-unknown/wasm-release/dprint_plugin_tex_fmt.wasm plugin.wasm
      - name: Generate release body
        run: |
          cat > release-body.md <<EOF
          ## Installation

          \`\`\`sh
          dprint add kjanat/tex-fmt
          \`\`\`

          Or add manually to \`dprint.json\`:

          \`\`\`json
          {
            "plugins": [
              "https://plugins.dprint.dev/kjanat/tex-fmt-${GITHUB_REF_NAME}.wasm"
            ]
          }
          \`\`\`

          EOF
      - uses: softprops/action-gh-release@v3
        with:
          files: |
            plugin.wasm
            schema.json
          body_path: release-body.md
          generate_release_notes: true
